module.exports = {
    RETRIEVE_START: 'TASKS_RETRIEVE_START',
    RETRIEVE_SUCCESS: 'TASKS_RETRIEVE_SUCCESS',
    RETRIEVE_ERROR: 'TASKS_RETRIEVE_ERROR',
    CREATE_START: 'TASKS_CREATE_START',
    CREATE_SUCCESS: 'TASKS_CREATE_SUCCESS',
    CREATE_ERROR: 'TASKS_CREATE_ERROR',
    UPDATE_START: 'TASKS_UPDATE_START',
    UPDATE_SUCCESS: 'TASKS_UPDATE_SUCCESS',
    UPDATE_ERROR: 'TASKS_UPDATE_ERROR',
    DESTROY_START: 'TASKS_DESTROY_START',
    DESTROY_SUCCESS: 'TASKS_DESTROY_SUCCESS',
    DESTROY_ERROR: 'TASKS_DESTROY_ERROR'
};